site_name: Lab TieD 6

site_author: Нікоаєнко Богдан Андрійович
site_description: 'Проста та зрозуміла документація лаборатоної роботи.'

# Налаштування зовнішнього вигляду
theme:

name: material
language: uk # Додамо українську мову для елементів інтерфейсу

# Налаштування структури навігаційного меню
nav:
- 'Головна': 'index.md'
- 'Посібник користувача':
- 'Встановлення': 'guide/installation.md'
- 'Приклади використання': 'guide/usage.md'
- 'Про проєкт': 'about.md'